//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanBilliards
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCao_DoanhThu
    {
        public int BaoCaoID { get; set; }
        public System.DateTime TuNgay { get; set; }
        public System.DateTime DenNgay { get; set; }
        public decimal TongDoanhThu { get; set; }
        public System.DateTime NgayLap { get; set; }
    }
}
