//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanBilliards
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonChiTiet
    {
        public int HoaDonCTID { get; set; }
        public int HoaDonID { get; set; }
        public int SanPhamID { get; set; }
        public decimal SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
