//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanBilliards
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.HoaDonChiTiets = new HashSet<HoaDonChiTiet>();
        }
    
        public int HoaDonID { get; set; }
        public int BanID { get; set; }
        public byte TrangThai { get; set; }
        public byte LoaiGiamGia { get; set; }
        public decimal GiaTriGiam { get; set; }
        public decimal TongThanhToan { get; set; }
        public Nullable<decimal> TongTienTruocGiam { get; set; }
        public System.DateTime ThoiDiemBatDau { get; set; }
        public Nullable<System.DateTime> ThoiDiemThanhToan { get; set; }
        public Nullable<int> NguoiLapID { get; set; }
    
        public virtual Ban Ban { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonChiTiet> HoaDonChiTiets { get; set; }
    }
}
