//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanBilliards
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        public int NhanVienID { get; set; }
        public string MaNV { get; set; }
        public int NguoiDungID { get; set; }
        public string HoTen { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> LuongCoBan { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
