//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanBilliards
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyQuanBilliardsEntities : DbContext
    {
        public QuanLyQuanBilliardsEntities()
            : base("name=QuanLyQuanBilliardsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<HoaDonChiTiet> HoaDonChiTiets { get; set; }
        public virtual DbSet<BaoCao_DoanhThu> BaoCao_DoanhThu { get; set; }
        public virtual DbSet<Ban> Bans { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<KhuVuc> KhuVucs { get; set; }
        public virtual DbSet<LoaiBan> LoaiBans { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
    
        public virtual ObjectResult<sp_ChuyenBan_Result> sp_ChuyenBan(Nullable<int> banCu, Nullable<int> banMoi)
        {
            var banCuParameter = banCu.HasValue ?
                new ObjectParameter("BanCu", banCu) :
                new ObjectParameter("BanCu", typeof(int));
    
            var banMoiParameter = banMoi.HasValue ?
                new ObjectParameter("BanMoi", banMoi) :
                new ObjectParameter("BanMoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ChuyenBan_Result>("sp_ChuyenBan", banCuParameter, banMoiParameter);
        }
    
        public virtual int sp_HuyHoaDon(Nullable<int> banID)
        {
            var banIDParameter = banID.HasValue ?
                new ObjectParameter("BanID", banID) :
                new ObjectParameter("BanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HuyHoaDon", banIDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_LayChiTietHoaDon(Nullable<int> banID)
        {
            var banIDParameter = banID.HasValue ?
                new ObjectParameter("BanID", banID) :
                new ObjectParameter("BanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_LayChiTietHoaDon", banIDParameter);
        }
    
        public virtual int sp_ThanhToanDayDu(Nullable<int> banID, Nullable<decimal> tongTienCuoiCung, Nullable<decimal> tongTienTruocGiam)
        {
            var banIDParameter = banID.HasValue ?
                new ObjectParameter("BanID", banID) :
                new ObjectParameter("BanID", typeof(int));
    
            var tongTienCuoiCungParameter = tongTienCuoiCung.HasValue ?
                new ObjectParameter("TongTienCuoiCung", tongTienCuoiCung) :
                new ObjectParameter("TongTienCuoiCung", typeof(decimal));
    
            var tongTienTruocGiamParameter = tongTienTruocGiam.HasValue ?
                new ObjectParameter("TongTienTruocGiam", tongTienTruocGiam) :
                new ObjectParameter("TongTienTruocGiam", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThanhToanDayDu", banIDParameter, tongTienCuoiCungParameter, tongTienTruocGiamParameter);
        }
    
        public virtual ObjectResult<sp_TinhTienBan_Result> sp_TinhTienBan(Nullable<int> banID)
        {
            var banIDParameter = banID.HasValue ?
                new ObjectParameter("BanID", banID) :
                new ObjectParameter("BanID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TinhTienBan_Result>("sp_TinhTienBan", banIDParameter);
        }
    
        public virtual ObjectResult<sp_BaoCaoDoanhThu_Result> sp_BaoCaoDoanhThu(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoDoanhThu_Result>("sp_BaoCaoDoanhThu", tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<sp_DongBoBaoCao_Result> sp_DongBoBaoCao(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay, Nullable<bool> ghiDe)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            var ghiDeParameter = ghiDe.HasValue ?
                new ObjectParameter("GhiDe", ghiDe) :
                new ObjectParameter("GhiDe", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DongBoBaoCao_Result>("sp_DongBoBaoCao", tuNgayParameter, denNgayParameter, ghiDeParameter);
        }
    
        public virtual ObjectResult<sp_XemBaoCaoTheoNgay_Result> sp_XemBaoCaoTheoNgay(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemBaoCaoTheoNgay_Result>("sp_XemBaoCaoTheoNgay", tuNgayParameter, denNgayParameter);
        }
    }
}
